apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
{{- if or (.Values.global.metrics.enabled) (.Values.metrics.enabled) }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
{{- end }}
    spec:
      securityContext:
        fsGroup: 101
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      containers:
        - name: app-map
          image: "{{ .Values.docker.registry | default .Values.global.docker.registry }}/bbkr/bbk-demo-demo-app:{{ .Values.docker.imageTag }}"
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
