apiVersion: v1
kind: ConfigMap
metadata:
  name: bbk-demo-postgres-init
  namespace: "{{ .Release.Namespace }}"
  labels: 
    {{include "bitbroker.labels" .}}
  annotations:
    helm.sh/hook: pre-install
data:
  init.sql: |
    /*
    The bit-broker connector database intialisation script.
    */

    \connect postgres

    -- clean up any previous assets - for development only

    DROP DATABASE IF EXISTS bbk_connector_data;

    DROP USER IF EXISTS bbk_connector;

    DROP ROLE IF EXISTS bbk_connector_reader;
    DROP ROLE IF EXISTS bbk_connector_writer;

    -- create the user and role assets

    CREATE ROLE bbk_connector_reader;
    CREATE ROLE bbk_connector_writer;

    CREATE USER bbk_connector WITH ENCRYPTED PASSWORD 'bbk_connector_pwd';

    GRANT bbk_connector_reader TO bbk_connector;
    GRANT bbk_connector_writer TO bbk_connector;

    -- create the database

    CREATE DATABASE bbk_connector_data WITH ENCODING = 'UTF8' OWNER = bbk_connector;

    -- create extensions

    \connect bbk_connector_data

    CREATE EXTENSION postgis;
