## Docker image
##
docker:
  imageTag: "latest"
  imagePullPolicy: "Always"
  imagePullSecret: "regcred"

  ## If private registry
  ##
  #registry: ""

## Number of replicas
##
replicaCount: 1

entity: "country"
connectorId: ""
token: ""

## Enable or disable metrics for Prometheus
##
metrics:
  enabled: false
