# Copyright 2022 Cisco and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Image to Docker Registry

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parse tag name
      run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> $GITHUB_ENV

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push to Docker Hub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/connector-nodejs-rdbms/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/bbk-connector-nodejs-rdbms:latest,${{ secrets.DOCKER_USERNAME }}/bbk-connector-nodejs-rdbms:${{ env.TAG_NAME }}
    - name: Push flyway migrator image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/flyway/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/bbk-demo-flyway-migrate:latest,${{ secrets.DOCKER_USERNAME }}/bbk-demo-flyway-migrate:${{ env.TAG_NAME }}
    - name: Push explorer app to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/app-explorer/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/bbk-demo-explorer-app:latest,${{ secrets.DOCKER_USERNAME }}/bbk-demo-explorer-app:${{ env.TAG_NAME }}
    - name: Push map app to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/app-map/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/bbk-demo-map-app:latest,${{ secrets.DOCKER_USERNAME }}/bbk-demo-map-app:${{ env.TAG_NAME }}
    - name: Push demo app to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/app-demo/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/bbk-demo-demo-app:latest,${{ secrets.DOCKER_USERNAME }}/bbk-demo-demo-app:${{ env.TAG_NAME }}
